// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: rpc/auth/v1/auth.proto

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Reason is nested so its values stay scoped to this message and need no
// enum-name prefix (top-level proto3 enum values share the package scope).
type ValidateTokenResponse_Reason int32

const (
	ValidateTokenResponse_UNSPECIFIED   ValidateTokenResponse_Reason = 0
	ValidateTokenResponse_MALFORMED     ValidateTokenResponse_Reason = 1
	ValidateTokenResponse_EXPIRED       ValidateTokenResponse_Reason = 2
	ValidateTokenResponse_WRONG_PURPOSE ValidateTokenResponse_Reason = 3
	ValidateTokenResponse_REVOKED       ValidateTokenResponse_Reason = 4 // reserved for the Redis session check (iteration 2)
)

// Enum value maps for ValidateTokenResponse_Reason.
var (
	ValidateTokenResponse_Reason_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "MALFORMED",
		2: "EXPIRED",
		3: "WRONG_PURPOSE",
		4: "REVOKED",
	}
	ValidateTokenResponse_Reason_value = map[string]int32{
		"UNSPECIFIED":   0,
		"MALFORMED":     1,
		"EXPIRED":       2,
		"WRONG_PURPOSE": 3,
		"REVOKED":       4,
	}
)

func (x ValidateTokenResponse_Reason) Enum() *ValidateTokenResponse_Reason {
	p := new(ValidateTokenResponse_Reason)
	*p = x
	return p
}

func (x ValidateTokenResponse_Reason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValidateTokenResponse_Reason) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_auth_v1_auth_proto_enumTypes[0].Descriptor()
}

func (ValidateTokenResponse_Reason) Type() protoreflect.EnumType {
	return &file_rpc_auth_v1_auth_proto_enumTypes[0]
}

func (x ValidateTokenResponse_Reason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValidateTokenResponse_Reason.Descriptor instead.
func (ValidateTokenResponse_Reason) EnumDescriptor() ([]byte, []int) {
	return file_rpc_auth_v1_auth_proto_rawDescGZIP(), []int{1, 0}
}

type ValidateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_rpc_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_rpc_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ValidateTokenResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Valid         bool                         `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	UserUuid      string                       `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	Reason        ValidateTokenResponse_Reason `protobuf:"varint,3,opt,name=reason,proto3,enum=auth.v1.ValidateTokenResponse_Reason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_rpc_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_rpc_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateTokenResponse) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *ValidateTokenResponse) GetReason() ValidateTokenResponse_Reason {
	if x != nil {
		return x.Reason
	}
	return ValidateTokenResponse_UNSPECIFIED
}

var File_rpc_auth_v1_auth_proto protoreflect.FileDescriptor

const file_rpc_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x16rpc/auth/v1/auth.proto\x12\aauth.v1\",\n" +
	"\x14ValidateTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\xe0\x01\n" +
	"\x15ValidateTokenResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x1b\n" +
	"\tuser_uuid\x18\x02 \x01(\tR\buserUuid\x12=\n" +
	"\x06reason\x18\x03 \x01(\x0e2%.auth.v1.ValidateTokenResponse.ReasonR\x06reason\"U\n" +
	"\x06Reason\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\r\n" +
	"\tMALFORMED\x10\x01\x12\v\n" +
	"\aEXPIRED\x10\x02\x12\x11\n" +
	"\rWRONG_PURPOSE\x10\x03\x12\v\n" +
	"\aREVOKED\x10\x042]\n" +
	"\vAuthService\x12N\n" +
	"\rValidateToken\x12\x1d.auth.v1.ValidateTokenRequest\x1a\x1e.auth.v1.ValidateTokenResponseB8Z6github.com/guille1988/go-app-shared/rpc/auth/v1;authv1b\x06proto3"

var (
	file_rpc_auth_v1_auth_proto_rawDescOnce sync.Once
	file_rpc_auth_v1_auth_proto_rawDescData []byte
)

func file_rpc_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_rpc_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_rpc_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_auth_v1_auth_proto_rawDesc), len(file_rpc_auth_v1_auth_proto_rawDesc)))
	})
	return file_rpc_auth_v1_auth_proto_rawDescData
}

var file_rpc_auth_v1_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rpc_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_auth_v1_auth_proto_goTypes = []any{
	(ValidateTokenResponse_Reason)(0), // 0: auth.v1.ValidateTokenResponse.Reason
	(*ValidateTokenRequest)(nil),      // 1: auth.v1.ValidateTokenRequest
	(*ValidateTokenResponse)(nil),     // 2: auth.v1.ValidateTokenResponse
}
var file_rpc_auth_v1_auth_proto_depIdxs = []int32{
	0, // 0: auth.v1.ValidateTokenResponse.reason:type_name -> auth.v1.ValidateTokenResponse.Reason
	1, // 1: auth.v1.AuthService.ValidateToken:input_type -> auth.v1.ValidateTokenRequest
	2, // 2: auth.v1.AuthService.ValidateToken:output_type -> auth.v1.ValidateTokenResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_auth_v1_auth_proto_init() }
func file_rpc_auth_v1_auth_proto_init() {
	if File_rpc_auth_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_auth_v1_auth_proto_rawDesc), len(file_rpc_auth_v1_auth_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_rpc_auth_v1_auth_proto_depIdxs,
		EnumInfos:         file_rpc_auth_v1_auth_proto_enumTypes,
		MessageInfos:      file_rpc_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_rpc_auth_v1_auth_proto = out.File
	file_rpc_auth_v1_auth_proto_goTypes = nil
	file_rpc_auth_v1_auth_proto_depIdxs = nil
}
